### ISSUE TITLE
Default configuration is only using compress gds

### ISSUE THREAD

**Issue by marwaneltoukhy** [d-m-bailey/extra_be_checks#28]
file `tech/sky130A.lvs_config.sh` looks only for compressed gds, which is not necessarily the case with all projects, some might not be compressed.

**Comment by d-m-bailey** [comment]
Good point. What if both the compressed file and uncompressed file exist and are different? Do we want to require the user to be explicit?

**Comment by marwaneltoukhy** [comment]
Precheck already breaks if that's the case, I think LVS should break as well

**Comment by d-m-bailey** [comment]
@marwaneltoukhy Sorry for the delayed response. The gds file in the `lvs_config.json` file is what is used be default. The user can set that to compressed or uncompressed. 
This value is overridable though, for example
```
$LVS_ROOT/run_be_checks lvs/user_project_wrapper/lvs_config.json user_project_wrapper user_project_wrapper gds/user_project_wrapper.gds
```
The first positional parameter after the lvs_config file is the source top level override, the second is the layout top level override, and the third is the gds override.
