### ISSUE TITLE
Bug in running CVC

### ISSUE THREAD

**Issue by marwaneltoukhy** [d-m-bailey/extra_be_checks#29]
Not sure why this [line](https://github.com/d-m-bailey/extra_be_checks/blob/f539f1a37b7d348c849148d854a96b72dce9340e/run_cvc#L26) is here, but it is causing the path to be wrong, my solution was

```
-BASE_NAME=${DESIGN_NAME//[A-Z0-9][A-Z0-9]_/} # remove leading 2 byte prefices
-if [[ (! -f $WORK_ROOT/$DESIGN_NAME/$DESIGN_NAME.power) && -f $LVS_ROOT/cvc/$BASE_NAME.$PDK.power ]]; then
-       cp $LVS_ROOT/cvc/$BASE_NAME.$PDK.power $WORK_ROOT/$DESIGN_NAME/$DESIGN_NAME.power
+# BASE_NAME=${DESIGN_NAME//[A-Z0-9][A-Z0-9]_/} # remove leading 2 byte prefices
+if [[ (! -f $WORK_ROOT/$DESIGN_NAME/$DESIGN_NAME.power) && -f $LVS_ROOT/cvc/$DESIGN_NAME.$PDK.power ]]; then
+       cp $LVS_ROOT/cvc/$DESIGN_NAME.$PDK.power $WORK_ROOT/$DESIGN_NAME/$DESIGN_NAME.power
```

**Comment by d-m-bailey** [comment]
@marwaneltoukhy Thanks. Probably should anchor it to the front. `make ship` will add 2 byte random prefixes to sub blocks including `user_project_wrapper`. This gives something like `A7_user_project_wrapper`. However, this block does not have a default power definition while `user_project_wrapper` does. What path is incorrect?

**Comment by marwaneltoukhy** [comment]
Not sure if what I'm going to claim is accurate so please correct me if I'm wrong; `make ship` will only add those 2 bytes if the error we saw/debugged earlier last week happens, where it tries to read in two files with the same name, once gds and once mag. If that's the case then that's something wrong with the build script that needs to be fixed.

Also, in my case I'm running directly on `user_project_wrapper` so I don't actually run `make ship` so that line messes with the name of the cell `user_project_wrapper` which is correctly defined in the variable `DESIGN_NAME` to make it something else, meaning the script is searching for the wrong cell name.

**Comment by d-m-bailey** [comment]
Not sure where the extra 2 byte prefix comes from either, but all the oasis files have it.

`${DESIGN_NAME//[A-Z0-9][A-Z0-9]_/}` this is just a global substitution on the `DESIGN_NAME` value - globally replacing `[A-Z0-9][A-Z0-9]_` with nothing. If `DESIGN_NAME`  is `user_project_wrapper`, it shouldn't change anything.

**Comment by marwaneltoukhy** [comment]
It changes `user_project_wrapper` to `usprojewrapper`

**Comment by d-m-bailey** [comment]
Here's a comparison:
```
user@chipignite-clear-dv-01:~/$ shopt nocasematch
nocasematch     off
user@chipignite-clear-dv-01:~/$ test_cell=AF_user_project_wrapper
user@chipignite-clear-dv-01:~/$ echo ${test_cell//[A-Z0-9][A-Z0-9]_}
user_project_wrapper

user@chipignite-clear-dv-01:~/$ shopt -s nocasematch 
user@chipignite-clear-dv-01:~/$ shopt nocasematch
nocasematch     on
user@chipignite-clear-dv-01:~/$ echo ${test_cell//[A-Z0-9][A-Z0-9]_}
usprojewrapper

user@chipignite-clear-dv-01:~/$ shopt -u nocasematch 
user@chipignite-clear-dv-01:~/$ shopt nocasematch
nocasematch     off
user@chipignite-clear-dv-01:~/$ echo ${test_cell//[A-Z0-9][A-Z0-9]_}
user_project_wrapper
```

**Comment by d-m-bailey** [comment]
I think this is fixed with `shopt -u nocasematch`, so I'll close it.

@marwaneltoukhy Please reopen if there are still problems.
