### ISSUE TITLE
Wrong Environment variable paths

### ISSUE THREAD

**Issue by marwaneltoukhy** [d-m-bailey/extra_be_checks#30]
Environment variables like `LOG_ROOT` and `SIGNOFF_ROOT` don't actually reflect the correct path, there's always `TOP_LAYOUT` in the hierarchy. I think it's better if the environment variables reflect where the files are.

**Comment by d-m-bailey** [comment]
The following syntax will prioritize the already defined values for these environment variables. 
```
: "${LVS_ROOT:=$(pwd)}"
: "${LOG_ROOT:=$(pwd)}"
: "${SIGNOFF_ROOT:=$(pwd)}"
: "${WORK_ROOT:=$(pwd)}"
```
The user/system is expected to define these before running the script.

Essentially does the same thing (assign a value if it doesn't have one) as this
```
echo ${PDK_ROOT:=/usr/share/pdk} > /dev/null
echo ${PDK:=sky130A} > /dev/null
```
but using less system resources.

I could replace these lines with a check that the variables are set, but I don't think a default of the current directory is unreasonable.

**Comment by marwaneltoukhy** [comment]
Yes, my issue is that after defining the environment variable, let's say `WORK_ROOT`, the script adds an extra hierarchy, for example here https://github.com/d-m-bailey/extra_be_checks/blob/f539f1a37b7d348c849148d854a96b72dce9340e/run_full_lvs#L68
where it adds `TOP_LAYOUT` or `TOP_SOURCE` directory, so there's always an extra directory that I didn't define, and don't need.

**Comment by d-m-bailey** [comment]
Got it. Thanks for reporting.

Working on fixing this and the return codes.

**Comment by d-m-bailey** [comment]
I think this is fixed in the current `precheck` branch.

@marwaneltoukhy Please reopen if there are still problems.
